### ISSUE TITLE
Create documentation for uw config validate mode.

### ISSUE THREAD

**Issue by venitahagerty** [ufs-community/uwtools#259]
**Description**
Create documentation for the command line tool validate_config.py

**Requirements**
This needs to be in its own chapter in the User's Guide, just like the documentation for set_config.py. The documentation needs to describe what the validation configuration tool does, its arguments, and the types of files expected. The validation schema is a json file in the jsonschema format https://github.com/ufs-community/workflow-tools/blob/develop/schema/workflow.jsonschema. This file is not complete, and needs to be expanded. The config file is a YAML file similar to the machine files in the SRW repo https://github.com/ufs-community/ufs-srweather-app/tree/develop/ush/machine. There is also additional default value information in https://github.com/ufs-community/ufs-srweather-app/blob/develop/ush/valid_param_vals.yaml. There are 2 test YAML files in tests/fixtures, good.yaml and bad,yaml.

**Comment by christinaholtNOAA** [comment]
Should be handled by upcoming Jira ticket TBD.
