### ISSUE TITLE
`set_template` should accept a dictionary describing the variables to fill in the template

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/uwtools#296]
**Description**
Currently the Jinja templater `set_template` in file `templater.py` requires that either the variables to fill come from environment variables or from a yaml-formatted config file specifying the required variables. While the capability to pass individual key-value pairs exists with the "config_items" argument, the documentation for this option is not clear, and it is clunky to pass large sets of key-value pairs manually, It would be desirable to also have the ability to pass a dictionary of variables, for instance, for cases where the templater is called from a python function that has the template variables in a dictionary already (such as in the SRW App file [`create_nems_configure_file.py`](https://github.com/ufs-community/ufs-srweather-app/blob/develop/ush/create_nems_configure_file.py)).

**Requirements**
`set_template` should accept a dictionary as an argument in lieu of a yaml file defining the template variables.

**Describe alternatives you've considered**
This seems like a no-brainer, since the logic to achieve this pretty much already exists.

**Acceptance Criteria (Definition of Done)**
I should be able to pass a dictionary via command line in lieu of providing a yaml file.

**Additional context**

**Comment by christinaholtNOAA** [comment]
We have developed this feature and plan to release it in the coming weeks. We will integrate it into SRW shortly thereafter.
