### ISSUE TITLE
Rocoto JSONSchema Metatasks var requirement bug (PR UW-381)

### ISSUE THREAD

**Issue by NaureenBharwaniNOAA** [ufs-community/uwtools#300]
**Expected behavior**

When we validate our Rocoto JSONSchema against a valid yaml within the `metatask` tag we require a `task` or `metatask` tag nested inside as a required property to pass validation. We would like to add the `var` property to the `metatask` tag to confirm a user is supplying the `var` property, which should be an 'entry with a nested dictionary of keys representing the names of the metatask variables and values indicating the list of values for each iteration is required.' We want to add the `var` property so if a user does not supply it, the yaml fails validation.

**Current behavior**

Currently, we validate our Rocoto JSONSchema against a valid yaml. Within the `metatask` tag we require a `task` or `metatask` tag nested inside as a required property to pass validation. However, the `metatask` tag also requires a property called `var` to pass validation. Our JSONSchema allows users to pass in a yaml without this `var` property and it will still pass validation.

**To Reproduce**

1. [Rocoto Documentation](http://christopherwharrop.github.io/rocoto/)
2. [Rocoto SRW Documentation](https://ufs-srweather-app.readthedocs.io/en/develop/CustomizingTheWorkflow/DefineWorkflow.html#defining-a-task)
3. [JSONSchema Resource](https://opis.io/json-schema/2.x/multiple-subschemas.html#oneof)

Currently fails and what we would like to add:
```
"metataskPattern": {
            "patternProperties": {
                "^metatask_.*$": {
                    "type": "object",
                    "properties": {
                        "var": {
                            "type": "object"
                        },
                        "$ref": "#/$defs/taskPattern",
                        "$ref": "#/$defs/taskPattern"
                    },
                    "anyOf": [
                        { 
                            "$ref": "#/$defs/metataskPattern"
                        },
                        { 
                            "$ref": "#/$defs/taskPattern" 
                        }
                    ]
                }
            },
            "additionalProperties": false
        }
```

**Context**

**Detailed Description**

Add the `var` property to the `metatask` tag and `require` that a user supply it. It should not be an optional property.

**Additional Information**

The issue comes in when supplying both the nested `metatask` tag and `task` tag requirement. We currently can either have the required `var` property required and validating correctly against the schema **_OR_** we can have the required nested `metatask` and `task` properties required and validating correctly against the schema. When we required both be supplied by the user it presents an error.

1. `var` property required and passing (without nested `metatask` or `task` tags):
```
"metataskPattern": {
            "patternProperties": {
                "^metatask_.*$": {
                    "type": "object",
                    "properties": {
                        "var": {
                            "type": "object"
                        }
                    }
                }
            },
            "additionalProperties": false
        }
```

5. nested `metatask` or `task` property required and passing (without the `var` property):
```
"metataskPattern": {
            "patternProperties": {
                "^metatask_.*$": {
                    "type": "object",
                    "properties": {
                        "$ref": "#/$defs/taskPattern",
                        "$ref": "#/$defs/taskPattern"
                    },
                    "anyOf": [
                        { 
                            "$ref": "#/$defs/metataskPattern"
                        },
                        { 
                            "$ref": "#/$defs/taskPattern" 
                        }
                    ]
                }
            },
            "additionalProperties": false
        }
```
**Possible Implementation**

```
"metataskPattern": {
            "patternProperties": {
                "^metatask_.*$": {
                    "type": "object",
                    "properties": {
                        "var": {
                            "type": "object"
                        },
                        "$ref": "#/$defs/taskPattern",
                        "$ref": "#/$defs/taskPattern"
                    },
                    "anyOf": [
                        { 
                            "$ref": "#/$defs/metataskPattern"
                        },
                        { 
                            "$ref": "#/$defs/taskPattern" 
                        }
                    ]
                }
            },
            "additionalProperties": false
        }
```

Example yaml file:
```
  workflow:
    attrs:
      realtime: false
      scheduler: slurm
      cyclethrottle: 5
    cycledefs:
      howdy: 
        - 202209290000 202209300000 06:00:00
        - 202210200000 202310201800 02:00:00
      groupname: 
        - 202209290000 202209300000 06:00:00
      groupname2: 
        - 202209290000 202209300000 06:00:00
    entities:
      ACCOUNT: myaccount
      FOO: test.log
    log: /some/path/to/&FOO;
    tasks:
      metatask_ensemble_hello1:
        metatask_ensemble_hello2:
          task_hello:
            command: hello
            walltime: 00:01:00
            cores: 3
```

Another layer:
If we remove `"additionalProperties": false` then we see that the JSONSchema does not traverse the yaml completely. This causes an issue when we have a `task` property under the `metatask` tag because we have three required `properties` of `task` which are `command`, `walltime` and `cores`. Within `"additionalProperties": false` we see that a user could supply a yaml that does not include one of these required `properties` causing further disruption down the line.

Our two options are:
1. For now leave the `var` property off completely and continue with `"additionalProperties": false` being included. This would mean a user would not be able to supply `var` at all.
2. We can allow a user to supply `var` and not make it `required`, then we would have to remove `"additionalProperties": false` and this would mean users could supply an invalid yaml without supplying all the `required properties` for `task`.

**Comment by maddenp-noaa** [comment]
Issue is resolved per reporter.
