### ISSUE TITLE
Error trying to reach documentation

### ISSUE THREAD

**Issue by benjamin-cash** [ufs-community/uwtools#403]
This started popping up since I looked at the documentation last (sometime yesterday)

Your connection is not private
Attackers might be trying to steal your information from uwtools.readthedocs.io (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_AUTHORITY_INVALID

**Comment by maddenp-noaa** [comment]
I am unable to replicate this, having tried on OSX, Linux, and Android systems, using both Chrome and Firefox.

Sometimes issues related to certificate validation can result from the system clock on the requesting system being incorrect. Can you check that and/or try a different computer?

**Comment by benjamin-cash** [comment]
Hi @maddenp-noaa - I was able to reach it from my android phone, but still unable to from my laptop (chrome and safari). Safari gave me the attached information. Not sure if that helps clear anything up. 

<img width="475" alt="Screenshot 2024-01-30 at 4 33 09 PM" src="https://github.com/ufs-community/uwtools/assets/62720073/83f12cc9-199b-49bf-9a86-8276544a579c">

**Comment by maddenp-noaa** [comment]
Here's a [Stack Exchange article](https://apple.stackexchange.com/questions/443268/macos-not-trusting-the-cisco-umbrella-root-ca) discussing this certificate. It sounds like this may result from some security software/appliance sitting between you and the Read the Docs site mediating your requests and potentially re-signing them with its own certificate, which your browser is not trusting. If you're using a company-issued system, I'd suggest talking to your IT department. If this is a personal system and the above doesn't make any sense, please let me know.

This is not, FWIW, the certificate that I see the Read the Docs pages signed with. Pages I visit are signed with a certificate issued by CloudFlare to Read the Docs.

**Comment by maddenp-noaa** [comment]
If you're administering your own system, maybe [this page](https://docs.umbrella.com/deployment-umbrella/docs/install-cisco-umbrella-root-certificate) will help.

**Comment by benjamin-cash** [comment]
Thanks for the help! This was working without issue yesterday, so I'm at a bit of a loss for why it's happening now. This is a university-managed laptop, so it's certainly not out of the question that they rolled something out which is causing an issue.

**Comment by benjamin-cash** [comment]
Seems highly likely that this is problem with remote management of my laptop so I will go ahead and close this.
