### ISSUE TITLE
translate does not preserve indentation 

### ISSUE THREAD

**Issue by benjamin-cash** [ufs-community/uwtools#406]
**Expected behavior**
translate using atparse should simply replace the @[] notation, leaving the rest of the file unchanged.

**Current behavior**

Leading spaces and tabs are being stripped out, removing indentation

**Machines affected**

Tested on Frontera, using both CLI and API 

**To Reproduce**
Can be reproduced using the following test file:
```
@[first_entry]
  @[second_entry]
  @[third_entry]
    @[fourth_entry]

        @[fifth entry]
```

**Comment by benjamin-cash** [comment]
Removing .strip() in atparse_to_jinja2.py appears to restore the expected behavior.

**Comment by maddenp-noaa** [comment]
I think the `.strip()` was meant to remove an unwanted trailing newline, but that could be handled with a more surgical `re.sub()`. We'll take a look.

**Comment by maddenp-noaa** [comment]
@benjamin-cash Your input shows `@[fifth entry]`, while the others have underscores in the "variable name" (e.g. `fourth_entry`). Is the input valid without the underscore?

**Comment by benjamin-cash** [comment]
@maddenp-noaa It probably wouldn't work if you then tried to replace that value via uw template render, but for uw template translate it's ok because that is just replacing the @[] with {{}} and doesn't care about what is enclosed.

**Comment by maddenp-noaa** [comment]
I'm not crazy about producing invalid Jinaj2 output, but we can wait for that bug report :)

**Comment by benjamin-cash** [comment]
@maddenp-noaa running the test now. :)
