### ISSUE TITLE
uwtools.api.file.copy cannot create nested directories

### ISSUE THREAD

**Issue by benjamin-cash** [ufs-community/uwtools#484]
The uwtools.api.file.copy tool uses os.mkdir, and will fail if a nested set of directories is specified. Unless there is some reason it is contra-indicated, recommend replacing os.mkdir with os.makedirs to allow for creation of nested directories.

**Comment by maddenp-noaa** [comment]
Thanks for the report. Definitely an oversight, as `link()` does create the parents correctly. Will fix.
