### ISSUE TITLE
`uwtools.api.config.realize` incorrectly prompts me to use `stdin_ok=True` flag when writing out from a dictionary or config object

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/uwtools#586]
**Expected behavior**
`uwtools.api.config.realize` should accept a dictionary (or a config object) for writing out a file. 

**Current behavior**
While this does appear to work, you get a spurious error that prompts you to include the `stdin_ok=True` flag, which doesn't make sense in the Python API context.

**Machines affected**
All. This was with uwtools release version 2.4.1.

**To Reproduce**
Here is a minimal reproducible example:

```
#!/usr/bin/env python3
  
"""
Example program demonstrating issue
"""

import uwtools.api.config as uwconfig

dict_to_write = {}
dict_to_write["test_field"]="test value"
uwconfig.realize(input_config=dict_to_write,output_file="test_output.yaml")
```

Run the above script with uwtools in your environment to reproduce:

```
$ python uw_issue_example.py 
Traceback (most recent call last):
  File "/scratch1/BMC/hmtb/HAFS/add_vx_workflow/HAFS/ush/uw_issue_example.py", line 11, in <module>
    uwconfig.realize(input_config=dict_to_write,output_file="test_output.yaml")
  File "/scratch1/BMC/hmtb/HAFS/add_vx_workflow/HAFS/ush/conda/envs/hafs_vx/lib/python3.12/site-packages/uwtools/api/config.py", line 131, in realize
    update_config=_ensure_data_source(_str2path(update_config), stdin_ok),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/BMC/hmtb/HAFS/add_vx_workflow/HAFS/ush/conda/envs/hafs_vx/lib/python3.12/site-packages/uwtools/utils/api.py", line 31, in ensure_data_source
    raise UWError("Set stdin_ok=True to permit read from stdin")
uwtools.exceptions.UWError: Set stdin_ok=True to permit read from stdin
```

Include the `stdin_ok=True` flag and you will get the expected output. But this flag should not be required from the API.

**Comment by maddenp-noaa** [comment]
Thank you for the report and valuable reproducer. I'm still looking, but this does indeed appear to be a bug. As a temporary workaround to suppress the noise, could you try adding an `update_config={}` parameter to the `realize()` call?

**Comment by mkavulich** [comment]
Thanks for the reply, including `update_config={}` also seems to suppress the error.

**Comment by maddenp-noaa** [comment]
We'll publish a `2.4.2` bugfix release tomorrow and I'll ping you here when it's ready for you to test.

**Comment by maddenp-noaa** [comment]
The `2.4.2` release is available on [GitHub](https://github.com/ufs-community/uwtools/releases/tag/v2.4.2) and [anaconda.org](https://anaconda.org/ufs-community/uwtools), so you should be able to `conda install -c ufs-community uwtools=2.4.2`, etc. If you are working from a git clone, the `2.4.2` branch corresponds to this release.
